version: '3'
services:
  springboot:
    build:
      context: ""
      dockerfile: docker/Dockerfile
    container_name: webflux-api
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - app-network
    environment:
      MONGO_URL: "mongodb://webflux-mongo:27017/webflux_db"
    volumes:
      - db-data:/var/www/volume
  mongo:
    image: mongo:3.6
    container_name: webflux-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: webflux_db
    networks:
      - app-network
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  app-network:
    driver: bridge
volumes:
  db-data: