server:
  port: 8080

spring:
  data.mongodb:
    uri: mongodb://webflux-mongo:27017/webflux_db

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: health,info